name: Go

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.78.2'
        # extended: true
    # - name: copy theme
    #   run: git clone https://github.com/spf13/hyde.git themes/hyde

    - name: Build
      run: hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.1
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        EXTERNAL_REPOSITORY: yfsoftcom/yfsoftcom.github.io
        PUBLISH_BRANCH: public
        PUBLISH_DIR: ./public

    - name: update repo site
      env:
        token: ${{ secrets.PAT }}
      run: |
        echo "yfsoftcom:$token" && \
        curl \
          -X PUT \
          -u "yfsoftcom:$token" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/yfsoftcom/yfsoftcom.github.io/pages \
          -d '{"cname":"blog.yunplus.io", "https_enforced": true}'
